{% set version = '3.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hunspell
  version: {{ version|replace("-", "_") }}

source:
  fn: hunspell_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/hunspell_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/hunspell/hunspell_{{ version }}.tar.gz
  sha256: 01fb9c87f7cf094aaad3b7098378134f2e503286224351e91d08c00b6ee19857

build:
  merge_build_host: True  # [win]
  number: 1002
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-digest
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-digest

test:
  commands:
    - $R -e "library('hunspell')"           # [not win]
    - "\"%R%\" -e \"library('hunspell')\""  # [win]

about:
  home: https://github.com/ropensci/hunspell#readme (devel) https://hunspell.github.io (upstream)
  license: GPL-2 | LGPL-2.1 | MPL-1.1
  summary: Low level spell checker and morphological analyzer based on the  famous 'hunspell'
    library <https://hunspell.github.io>. The package can analyze or check individual
    words as well as parse text, latex, html or xml documents. For a more user-friendly
    interface use the 'spelling' package which builds on this package to automate checking
    of files, documentation and vignettes in all common formats.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
