appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: hcbipNJ0yhQ4C/g63VLrOnmUZKPKL8v+IPvuCTZak8LMpB2d+oe+t+I7Cf34eh3ebWcsplYxAy5F7meLI2bUykeSiP2s+dZ1JiZXxwrktbTxhWb88j4kamTpmxRzt6oXbC9Q5/jasP+Cz4wQLX8YZ4XEIQ4awrrhkLzlDACEhwIi2xJlVRvXqDd4oPYMU0DMRHmo9zraXJLtYnUYL0eIgXPLvWDNFLe+/9dU09n7NlRK0yNSJ+P1tGWHhnTH+Q3yuAUZNX9sNsKkx9ogdeL/zasZiFkpMv5G3+aIxH1oOuQ3CJ9NP3ti+8R75DfxIf9hMJ05w1iq6ISiTABzjW3o+/6KDNoTHwntRLjMqY9tOO1WWt4TycGCw+DY56LzvimvzZzB7nLsv3vWTKZrM3+6ZHZgH54t3dv7TyiYVzHM3rlxrYybv+hfCQfZ6wF6KMUxOh1PykGUXzpmEYCBx0PQph5ITaPotqWmeg2B56pWbH93EDMmXypzBlyELJcjwbvxhDSC5E6d07BIHTMZA2WVVi9U2irh9Y2PkmW5nm3BdyCdLHOqNf3HHhbm9SSfbbSTVauZNuoNDVQfQ4hxkLR4g5a8pJ0WRfNpXXP5jCwRKxi3/FxIWqCz388K8L+u5GslAYxXbA+ZfzENykvKIEqyABZSj7bkXvnvfE0PUk+g1UU=}
bot:
  automerge: true
